### ISSUE TITLE
Float doesn't work as initialization for `sample`.

### ISSUE THREAD

**Issue by SiegeLordEx** [stan-dev/cmdstanpy#156]
#### Summary:
The documentation for `sample` in version 0.6.0 says that in addition to strings and dictionaries, single non-negative floats should also work, but in actuality they raise an error.

#### Description:
Consider this code:

```python
import cmdstanpy

code = """
parameters {
  real x;
}
model {
  x ~ normal(0, 1);
}
"""

filename = '/tmp/stan_test.stan'
with open(filename, 'w') as f:
  f.write(code)

model = cmdstanpy.CmdStanModel(stan_file=filename)
model.compile()
model.sample(inits=0.)
```

This raises the error:

```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    model.sample(inits=0.)
  File "/usr/local/google/home/siege/.local/lib/python3.7/site-packages/cmdstanpy/model.py", line 530, in sample                           
    with MaybeDictToFilePath(data, inits) as (_data, _inits):
  File "/usr/local/google/home/siege/.local/lib/python3.7/site-packages/cmdstanpy/utils.py", line 84, in __init__                          
    raise ValueError('data must be string or dict')
ValueError: data must be string or dict
```

Changing it to `model.sample(inits={'x': 0.})` works, but shouldn't be necessary according to the documentation.

#### Current Version:
0.6.0

**Comment by mitzimorris** [comment]
thanks, good catch!   will investigate.

**Comment by mitzimorris** [comment]
https://github.com/stan-dev/cmdstanpy/pull/172
