### ISSUE TITLE
Stan model error output is unreadable

### ISSUE THREAD

**Issue by evgenyneu** [stan-dev/cmdstanpy#193]
#### Summary:

If there are syntax errors in *.stan file, the error output is messy.

#### Description:

Use the code below and run it from the Terminal

```
python eight_schools.py
```

The eight_schools.stan model has a syntax error (missing semicolon in declaration of `tau` parameter), so Stan complains. The problem is that the error messages are not printed very nicely and are hard to read:

```
INFO:cmdstanpy:stan to c++ (/Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.hpp)
ERROR:cmdstanpy:file /Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.stan, exception RuntimeError('ERROR\n SYNTAX ERROR, MESSAGE(S) FROM PARSER:\n error in \'/Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.stan\' at line 10, column 2\n  -------------------------------------------------\n     8:   real mu;                // population treatment effect\n     9:   real<lower=0> tau       // MISSING SEMICOLON, standard deviation in treatment effects\n    10:   vector[J] eta;          // unscaled deviation from mu by school\n         ^\n    11: }\n  -------------------------------------------------\n\nPARSER EXPECTED: ";"\n\nmake: *** [/Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.hpp] Error 253 ')
ERROR:cmdstanpy:model compilation failed
Traceback (most recent call last):
  File "eight_schools.py", line 3, in <module>
    model = CmdStanModel(stan_file="eight_schools.stan")
  File "/opt/miniconda3/lib/python3.7/site-packages/cmdstanpy/model.py", line 138, in __init__
    self._stan_file
ValueError: unable to compile Stan model file: /Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.stan
deleting tmpfiles dir: /var/folders/4s/0b1x7wr50dbdvx5skpv8j0sm0000gn/T/tmpfsltbmq5
done
```

Is there a way to make the error messages more readable? In particular, I would like to quickly see what is the problem in my *.stan file and what's the line number. As you can see, this is a bit hard to decipher from the output at the moment. Thanks :)

#### Current Version:

0.8.0

### eight_schools.py

```Python
from cmdstanpy import CmdStanModel

model = CmdStanModel(stan_file="eight_schools.stan")

data = {
    "J": 8,
    "y": [28,  8, -3,  7, -1,  1, 18, 12],
    "sigma": [15, 10, 16, 11,  9, 11, 10, 18]
}

fit = model.sample(data=data)
print(fit.summary())
```

### eight_schools.stan

```Stan
// saved as 8schools.stan
data {
  int<lower=0> J;         // number of schools
  real y[J];              // estimated treatment effects
  real<lower=0> sigma[J]; // standard error of effect estimates
}
parameters {
  real mu;                // population treatment effect
  real<lower=0> tau       // MISSING SEMICOLON, standard deviation in treatment effects
  vector[J] eta;          // unscaled deviation from mu by school
}
transformed parameters {
  vector[J] theta = mu + tau * eta;        // school treatment effects
}
model {
  target += normal_lpdf(eta | 0, 1);       // prior log-density
  target += normal_lpdf(y | theta, sigma); // log-likelihood
}

```

**Comment by ahartikainen** [comment]
Yeah, I think we should parse the output and look for specific errors

**Comment by evgenyneu** [comment]
I think it would just be enough if the new line character '\n' is not escaped. Here is how the output looks if I replace \n with new line:

```
INFO:cmdstanpy:stan to c++ (/Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.hpp)
ERROR:cmdstanpy:file /Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.stan, exception RuntimeError('ERROR
 SYNTAX ERROR, MESSAGE(S) FROM PARSER:
 error in \'/Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.stan\' at line 10, column 2
  -------------------------------------------------
     8:   real mu;                // population treatment effect
     9:   real<lower=0> tau       // MISSING SEMICOLON, standard deviation in treatment effects
    10:   vector[J] eta;          // unscaled deviation from mu by school
         ^
    11: }
  -------------------------------------------------

PARSER EXPECTED: ";"

make: *** [/Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.hpp] Error 253 ')
ERROR:cmdstanpy:model compilation failed
Traceback (most recent call last):
  File "eight_schools.py", line 3, in <module>
    model = CmdStanModel(stan_file="eight_schools.stan")
  File "/opt/miniconda3/lib/python3.7/site-packages/cmdstanpy/model.py", line 138, in __init__
    self._stan_file
ValueError: unable to compile Stan model file: /Users/evgenii/Documents/2019_summer_project/logbook/a2020/a01/05_python_model/code/for_github/eight_schools.stan
deleting tmpfiles dir: /var/folders/4s/0b1x7wr50dbdvx5skpv8j0sm0000gn/T/tmpfsltbmq5
done
```

This is now much easier to digest. :)

**Comment by evgenyneu** [comment]
In comparison, here is the output from cmdstan:

```
$ make /Users/evgenii/Downloads/eight_schools

--- Translating Stan model to C++ code ---
bin/stanc  --o=/Users/evgenii/Downloads/eight_schools.hpp /Users/evgenii/Downloads/eight_schools.stan
Model name=eight_schools_model
Input file=/Users/evgenii/Downloads/eight_schools.stan
Output file=/Users/evgenii/Downloads/eight_schools.hpp

SYNTAX ERROR, MESSAGE(S) FROM PARSER:
 error in '/Users/evgenii/Downloads/eight_schools.stan' at line 10, column 2
  -------------------------------------------------
     8:   real mu;                // population treatment effect
     9:   real<lower=0> tau       // MISSING SEMICOLON, standard deviation in treatment effects
    10:   vector[J] eta;          // unscaled deviation from mu by school
         ^
    11: }
  -------------------------------------------------

PARSER EXPECTED: ";"

make: *** [/Users/evgenii/Downloads/eight_schools.hpp] Error 253
```

**Comment by ahartikainen** [comment]
What file did you change?

**Comment by evgenyneu** [comment]
@ahartikainen please find the changes in the pull request https://github.com/stan-dev/cmdstanpy/pull/194
