### ISSUE TITLE
Cmstanpy can not compile model

### ISSUE THREAD

**Issue by Dpananos** [stan-dev/cmdstanpy#272]
#### Summary:
Similar issues to #108. In that issue, installing cmdstanpy in a new env seemed to solve the issue.  I've installed cmdstanpy in a new conda environment. When I try to compile my model, I get the following error:

```
INFO:cmdstanpy:compiling stan program, exe file: /var/folders/bp/7wzcfkhj67l2f8d9mlr4zytc0000gn/T/tmp5j8wvysr/tmpohhihkwl
INFO:cmdstanpy:compiler options: stanc_options=None, cpp_options=None
ERROR:cmdstanpy:file /var/folders/bp/7wzcfkhj67l2f8d9mlr4zytc0000gn/T/tmp5j8wvysr/tmpohhihkwl.stan, exception ERROR
 error: PCH file uses a newer PCH format that cannot be read
1 error generated.
make: *** [/var/folders/bp/7wzcfkhj67l2f8d9mlr4zytc0000gn/T/tmp5j8wvysr/tmpohhihkwl] Error 1 
ERROR:cmdstanpy:model compilation failed

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-9623dea85d80> in <module>
----> 1 model= cmdstanpy.CmdStanModel(stan_file='models/model.stan')

~/miniconda3/envs/stan/lib/python3.8/site-packages/cmdstanpy/model.py in __init__(self, model_name, stan_file, exe_file, compile, stanc_options, cpp_options, logger)
    152             self.compile()
    153             if self._exe_file is None:
--> 154                 raise ValueError(
    155                     'Unable to compile Stan model file: {}.'.format(
    156                         self._stan_file

ValueError: Unable to compile Stan model file: /Users/demetri/Documents/PhD Code/PKBayes2/models/model.stan.
```

#### Description:
Here is some model code to replicate the error:

```
import cmdstanpy

model_code = '''
data{
    int N;
    vector[N] y;
}
parameters{
    real mu;
}
model{
    mu ~ normal(0,1);
    y~normal(mu,1);
}
'''

with open('test.stan','w') as file:
    file.write(model_code)

model = cmdstanpy.CmdStanModel(stan_file='test.stan')
```

#### Current Version:

```
# Name                    Version                   Build  Channel
cmdstanpy                 0.9.63                   pypi_0    pypi

```

**Comment by mitzimorris** [comment]
looks like a precompiled headers problem.
what version of CmdStan do you have installed?
if you run function `install_cmdstan()` again, this will give you 2.24.0  - if you don't have 2.24.0, you should definitely get it - the makefiles are smarted.

**Comment by Dpananos** [comment]
Great, solved.

**Comment by saurabhr** [comment]
Getting this error when i run install_cmdstan()

```
ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [make/command:13: bin/stansummary] Error 1
Compiling:  (05:09) | █████████████████████████▎                         |  ... 
Traceback (most recent call last):
  File "/Users/saurabh.ranjan/opt/anaconda3/envs/cmdstan/lib/python3.10/site-packages/cmdstanpy/install_cmdstan.py", line 114, in build
    do_command(cmd)
  File "/Users/saurabh.ranjan/opt/anaconda3/envs/cmdstan/lib/python3.10/site-packages/cmdstanpy/utils.py", line 1089, in do_command
    raise RuntimeError(msg)
RuntimeError: Command ['make', 'build', '-j1']
	error during processing No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/saurabh.ranjan/opt/anaconda3/envs/cmdstan/lib/python3.10/site-packages/cmdstanpy/install_cmdstan.py", line 223, in rebuild_cmdstan
    build(verbose, progress, cores)
  File "/Users/saurabh.ranjan/opt/anaconda3/envs/cmdstan/lib/python3.10/site-packages/cmdstanpy/install_cmdstan.py", line 123, in build
    raise CmdStanInstallError(f'Command "make build" failed\n{str(e)}')
cmdstanpy.install_cmdstan.CmdStanInstallError: Command "make build" failed
Command ['make', 'build', '-j1']
	error during processing No such file or directory
```

**Comment by WardBrian** [comment]
Hi @saurabhr, this looks like a duplicate of #546 

I just released a new version of cmdstan on conda earlier today which attempts to officially support the M1 Macs. If this does not work for you, you should be able to use the pip version of cmdstan instead

**Comment by saurabhr** [comment]
hi, i just installed cmdstan from conda but fail to run my models, I am using macOs BigSur (v 11.6.1) on intel i7 machine....i have also updated llvm, GCC and installed xcode-select, but keep getting this error.

**Comment by WardBrian** [comment]
You should make sure that cmdstan and it’s dependencies from conda are not using the x86 versions, as this will lead to your error above. The new ARM version should fix this, but I’m unable to test it myself. If you are unable to do this, you should not install cmdstanpy through conda and fall back to using pip (you can do this from inside a conda environment still)

**Comment by saurabhr** [comment]
thanks a lot @WardBrian , this seems to be working, now onto making pystan work coz lot of my scripts use that.
