### ISSUE TITLE
Sampling with single data json and multiple init jsons

### ISSUE THREAD

**Issue by mike-lawrence** [stan-dev/cmdstanpy#335]
This is my first foray into using cmdstanpy, so possibly I have invalid expectations, but I'm getting an error when I try to sample using a value for `data` that is a path string pointing to the data json and a value for `inits` that is a list of path strings pointing to a json for each chain: 

```python
import json
import cmdstanpy


def get_inits(fit, checkpoint_name="init_checkpoint"):
    params_bool = [not item.endswith("__") for item in fit.column_names]
    params = [item for item in fit.column_names if not item.endswith("__")]
    names = []
    for i, init in enumerate([item[params_bool].tolist() for item in fit.draws(inc_warmup=True)[-1]], 1):
        names.append(checkpoint_name + f"_chain_{i}" + ".json")
        with open(names[-1], "w") as f:
            json.dump(dict(zip(params, init)), f)
    return names


def get_stepsize(fit):
    return fit.stepsize.tolist()


def get_metric(fit, checkpoint_name="metric_checkpoint"):
    names = []
    for i, metric in enumerate([item.tolist() for item in fit.metric], 1):
        names.append(checkpoint_name + f"_chain_{i}" + ".json")
        with open(names[-1], "w") as f:
            json.dump({"inv_metric": metric}, f)
    return names

model = cmdstanpy.CmdStanModel(stan_file="hwg_fast.stan")

#this one runs fine
fit_warmup = model.sample(
    data='data_for_stan.json',
    iter_warmup=1000,
    iter_sampling=0,
    save_warmup=True,
)

inits = get_inits(fit_warmup)
stepsize = get_stepsize(fit_warmup)
metric = get_metric(fit_warmup)

#this one throws an error
fit_samples = model.sample(
    data='data_for_stan.json',
    iter_warmup=0,
    iter_sampling=5000,
    step_size=stepsize,
    metric=metric,
    adapt_engaged=False,
    inits=inits,
)
```
Here's the error:
```
Traceback (most recent call last):
  File "reprex.py", line 44, in <module>
    fit_samples = model.sample(
  File "/home/mike/.local/lib/python3.8/site-packages/cmdstanpy/model.py", line 687, in sample
    with MaybeDictToFilePath(data, inits) as (_data, _inits):
  File "/home/mike/.local/lib/python3.8/site-packages/cmdstanpy/utils.py", line 941, in __init__
    raise ValueError('data must be string or dict')
ValueError: data must be string or dict
deleting tmpfiles dir: /tmp/tmpehzgmod_
done
```

If I remove the `inits=inits,` line at the end, everything runs fine. 
If I make it `inits=inits[0]` at the end, everything runs fine.
~~If I have the data as a python dict instead of a path string pointing to the equivalent json file, everything runs fine.~~ (Edit: it throws the same error when the dict is entered in the script by hand)

So this seems to be specifically about the combination of an inits that's a multi-item list and a data that is a path string. 

I tried doing `data = ['data_for_stan.json' for i in range(len(inits))]`, but no luck.

**Comment by ahartikainen** [comment]
Can you try against github develop?

**Comment by mike-lawrence** [comment]
Sure, that's achieved by installing via `pip install -e git+https://github.com/stan-dev/cmdstanpy#egg=cmdstanpy`, correct?

**Comment by mike-lawrence** [comment]
I just tried @ahartikainen 's suggestion to import the data via:

```python
with open("data_for_stan.json") as f:
    data_for_stan = json.load(f)
```
then do `data=data_for_stan` in the calls to `sample()`, but I get the same error as originally reported.

**Comment by mitzimorris** [comment]
> So this seems to be specifically about the combination of an inits that's a multi-item list and a data that is a path string.

what does the json file look like?

**Comment by mike-lawrence** [comment]
It was created using `cmdstanr::write_stan_json()`, here's the contents:

```json
{
  "uW": [
    [1, -0.5, -0.5, 0.25],
    [1, 0.5, -0.5, -0.25],
    [1, -0.5, 0.5, -0.25],
    [1, 0.5, 0.5, 0.25]
  ],
  "num_subj": 10,
  "obs": [0.610680167856867, 0.74822302462722, 0.452712304417278, -0.31375592886679, 0.0450589512579251, 0.651254373388575, 0.513086615899667, 0.165736271278324, 0.473935184557499, 0.212697303883905, -0.911280016987296, -1.53429682723495, -0.865067343383669, -0.908982354375981, -0.977407585337516, -0.994644923604997, -0.905647218287424, -1.24430814822021, -1.04633070191888, -0.75364567972528, -1.82794609080714, -2.1856070266924, -2.2833269775058, -2.58012604723603, -2.77648802138611, -2.53716371712617, -1.77073439613416, -1.95081365757325, -2.32135078948267, -2.39806000540213, -1.88283478708851, -1.35375274919664, -1.82932672840831, -1.25696436415014, -1.48464848401104, -1.24078757044725, -2.05257918056009, -1.72315325796635, -2.05542254405448, -1.50348640149306, 0.854764993716532, 0.704596529595749, 1.35406820951525, 0.895606128966829, 1.18239484097607, 1.1021769792517, 0.51978612419252, 0.579864759303579, 0.827436918150178, 0.387658568939929, -1.67696723925706, -2.37101808602678, -1.28510539577376, -2.07954804782456, -1.26535780569577, -2.04660044809552, -2.25575973351795, -1.88297623330676, -1.88219437370006, -2.5202680228665, 0.197084034189076, -0.614997364688768, -0.0712496397483278, -0.0117718992628255, -0.145070450451246, -0.241041570790305, -0.122788868462928, -0.59597597572091, -0.496778441046085, -0.61281747779975, -0.666267796618892, -0.697009421816817, -1.15853714547058, -1.71735447374767, -1.25806704504276, -0.691832994868515, -1.43442240494631, -0.958530882430513, -1.62061590351214, -0.99908870944518, -0.519296839230624, -0.622376066346898, -0.519690214197077, -0.487141565413866, -0.502423204488094, 0.114837504325325, -0.136543895491684, -0.283114356855608, -0.568119973920548, -0.541749663193034, 0.424823325089373, 0.293323239695318, 0.544249174643435, 0.887977661544287, 0.270616040089624, 1.26107911143581, 0.221693526444758, 0.675644426653033, 1.59716722875962, 1.04449771816956, -1.37760826646973, -1.60687524789652, -1.06569324204383, -1.28806060606447, -1.42344502842834, -1.16459961447427, -1.46602325352026, -0.289960156677261, -0.655535911424009, -0.992084103495704, 1.16022616991023, 0.690870706026501, 1.22469566803634, 0.763466958921137, 0.517056983109718, 1.59737995011785, 0.546606866666336, 0.78379308775792, 0.663942068620787, 0.539841964324415, -0.492080703176664, -1.28519543770151, -0.792933690763134, -0.930478207108278, -1.23533171260214, -0.742202051393235, -0.87689025578773, -0.937177811924642, -0.349292100018483, -0.516953293056914, -1.78280106834712, -1.69052842183004, -2.02450138409309, -1.82423374764319, -1.33716881330919, -1.75525981198324, -1.68854874873634, -0.992441106276626, -2.01194008672962, -1.38999762121392, 0.413968274553515, -0.652683841296402, -0.248464061295417, -0.400745038288025, -0.438455763324237, -0.645790850657079, -0.589927157107037, 0.219257846083301, -0.0331628516735297, 0.0347650093011788, -0.578526173669966, -1.29697812086501, -0.855334428023569, -1.18310063651196, -1.34778632247187, -0.814416945059178, -1.14664227119187, -1.55883439551394, -1.24954441945448, -0.601747637600921, 0.494120128822352, -0.488540323812406, 0.0916562956614011, 0.372871730240722, -0.550812535505229, 0.582453784948565, -0.146292913718584, 0.160262386446591, -0.0163406008900196, 0.645076299251365, -1.8096100265794, -1.31229888544531, -1.61443380069662, -1.10635900810585, -0.425292176358264, -1.8241636243775, -1.2813226567215, -1.31329377073252, -0.682242653578068, -1.62513993721894, -1.21904732030208, -0.770524106726318, -1.50202107624368, -1.66836905174056, -1.4648208826973, -1.21727483354385, -1.78330923339594, -0.801236856893286, -1.40248770132638, -2.49002366134715, -1.94827974019008, -0.956328003648491, -1.89957971526155, -1.57251011937088, -1.51864648120573, -2.13120336023012, -1.35113089390871, -1.37704904830099, -0.834390817375297, -1.14803227878178, 0.482488739882523, 0.4210846193479, 0.678381870132622, 0.120331684640613, 0.491311119633194, 0.583773009755007, 0.657576775801749, 0.0280724122310803, 0.998333803344192, 0.71426884746253, 2.21398014809463, 0.57097084515396, 1.05680143236602, 0.63655644583235, 1.11987983022856, 1.39307310950557, 1.91336016734438, 1.11151486800139, 0.829326608822931, 1.16233329623564, -2.86042404435384, -3.02451504902427, -2.59985749263037, -3.20417229947342, -3.70834858998334, -2.73695214774012, -3.5084066663937, -2.86195144083841, -2.90061447453869, -2.9544336162122, 0.937730969513914, 0.216563854915508, -0.19746392384778, 0.317308007586582, 0.206911288455066, 0.530883618153565, 0.904382387759048, -0.382098597805253, 0.213671253752453, 0.319883249326616, 2.201700997843, 1.7359293419199, 2.14223701901583, 2.13881633292864, 1.99167726660318, 1.94980474583827, 2.5443557192833, 2.24811670194849, 2.7273269707949, 1.89577209323515, -0.719334383064378, -0.402158518418433, -0.21790977784657, -0.34337674057636, -0.408183705525852, -0.843636637882894, -0.552208033496391, -0.66391595542411, -0.139101582685261, -0.125468294495726, -1.46757634496538, -2.16599672899226, -1.68850267032403, -2.2219482337391, -2.60891621074716, -1.88050590104614, -2.23699942957618, -2.35470886775946, -2.32559693509227, -1.63577477396907, 0.230354359403664, 0.0192141073170538, -0.459258482864027, -0.846559139326145, -0.274026192137165, 0.0588471694124513, -0.044295889539357, -0.239671325050223, -0.274159122885427, -0.672412299661278, -0.847614328025902, -0.99259523697927, -0.988045892686571, -1.08890792166838, -1.44614135611154, -1.23492509092361, -0.727200495508491, -0.998898407970875, -1.00797121987717, -1.08306218564283, -1.85383935646168, -2.37026882588569, -2.28406289453925, -2.32141907885304, -2.73709218528492, -2.40201162825867, -1.89631217871508, -2.20599559828598, -2.91973254342378, -2.34827676868787, -1.41643105074169, -1.65364238787731, -1.33317998326934, -1.69015662385452, -2.01845864786252, -1.35307573271018, -1.52749230750291, -1.42249822902815, -1.23664170586828, -1.55183927643302, -3.28013763781, -2.62601163069109, -3.28306845631855, -2.86966532545398, -2.31489234093405, -3.31416721546482, -2.63151167610762, -2.89867038064992, -2.78378235023823, -2.30647662668887, 0.307967804073004, 0.621239281806165, -0.285847554767943, -0.18729929607761, -0.144519601779435, 0.089139441496342, -0.236749064210597, -0.168769009001834, -0.226567410004842, 0.363381001971505, 1.27940400223811, 1.41677613562584, 2.06885272035568, 1.00699338683673, 1.33030586289914, 2.29485678821757, 1.28381793156027, 1.04855859617238, 0.710989788933033, 0.870112813651287, -3.61924728413489, -3.57578396327302, -3.1395854232567, -2.86895754100426, -2.97315428614399, -3.1339889813154, -3.66802033360514, -2.74195460247733, -2.81652068009266, -2.38420099841087, -0.391825988108621, 0.194574477663047, 0.95576260326314, 0.345245871876397, 0.818979475320808, 0.516307503958958, 0.352747802238154, 0.643348100877006, -0.371138929507363, 0.174749596605997, 2.74300572898671, 3.01759141731246, 2.80317254708884, 2.58885882385788, 2.94264997319802, 2.52165305259394, 2.10347018602283, 2.50707028340071, 2.45531517560772, 2.65474679829951, -0.492426906659362, -0.106151797729638, 0.420098866463113, -1.02145418196613, -0.131887323991498, -0.620189968322156, -0.585220245168516, -1.02876327629771, -0.447014676798073, -0.225093446597471, -4.2341444860644, -2.97650064611784, -3.98467895065428, -4.55235161135401, -3.74349282791175, -2.82209609622118, -3.10440526371141, -3.22355436405877, -3.40607498216413, -3.52844878709067, -1.88777242027746, -2.28748449761425, -2.55469925238941, -2.1645019759475, -2.39022192800359, -2.09322619819692, -1.45188316072564, -2.05465229391475, -2.29893117356483, -2.11432132124754],
  "obs_index": [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
  "num_obs_total": 400,
  "num_rows_uW": 4,
  "num_cols_uW": 4
}
```

**Comment by mike-lawrence** [comment]
Oh, I made an error in the initial post: I said that if the data is a hand-typed dict, everything works fine, and I based this off @ahartikainen's success at using the above code with such data, but I just double-checked on my machine and it doesn't work (throws the same error).

**Comment by mitzimorris** [comment]
what version are your running?  I think this was fixed here:  https://github.com/stan-dev/cmdstanpy/pull/320

**Comment by mitzimorris** [comment]
we should update what's on pip.
lost track of time...

**Comment by mike-lawrence** [comment]
0.9.67

**Comment by mitzimorris** [comment]
that was October - fix went in November - we'll do a 2021 release this week.

**Comment by mike-lawrence** [comment]
Ah! That's it! And sorry, I thought I had pulled the develop version and installed that but there was a weird permissions thing and I think the old version stuck around. After a thorough purge and reinstall of the develop version, it runs fine.
