### ISSUE TITLE
Runtime Error: ERROR when running the "default" testing code

### ISSUE THREAD

**Issue by andreamoro** [stan-dev/cmdstanpy#401]
#### Description:
I have been suggested to run CmdStabPy with FBProphet to attempt resolving some (apparently) compatibility issues. I've completed the setup and I am nowrunning the default example in the home page, but I get the following error:

```
>>> import os
>>> from cmdstanpy import cmdstan_path, CmdStanModel
>>> bernoulli_stan = os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.stan')
>>> bernoulli_data = os.path.join(cmdstan_path(), 'examples', 'bernoulli', 'bernoulli.data.json')
>>> bernoulli_model = CmdStanModel(stan_file=bernoulli_stan)
INFO:cmdstanpy:found newer exe file, not recompiling
INFO:cmdstanpy:compiled model file: /Users/andreamoro/.cmdstanpy/cmdstan-2.27.0/examples/bernoulli/bernoulli
>>> bernoulli_fit = bernoulli_model.sample(chains=4, data=bernoulli_data)
INFO:cmdstanpy:start chain 1
INFO:cmdstanpy:start chain 2
INFO:cmdstanpy:start chain 3
INFO:cmdstanpy:start chain 4
INFO:cmdstanpy:finish chain 4
INFO:cmdstanpy:finish chain 3
INFO:cmdstanpy:finish chain 2
INFO:cmdstanpy:finish chain 1
>>> bernoulli_fit.summary()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andreamoro/.pyenv/versions/3.9.1/lib/python3.9/site-packages/cmdstanpy/stanfit.py", line 461, in summary
    do_command(cmd, logger=self.runset._logger)
  File "/Users/andreamoro/.pyenv/versions/3.9.1/lib/python3.9/site-packages/cmdstanpy/utils.py", line 733, in do_command
    raise RuntimeError(msg)
RuntimeError: ERROR
 The following argument was not expected: --csv_file=/var/folders/c_/ll8fp86d39d2qthh_cbg8vlc0000gp/T/tmp5usseznd/stansummary-bernoulli-4-chain-sgm0_tyu.csv
Run with --help for more information.
```

#### Additional Information:
Python 3.9.1 installed via pyenv

**Comment by mitzimorris** [comment]
OK, will investigate.
what version of CmdStanPy, and what OS are you using?

**Comment by andreamoro** [comment]
I'm on Mac OS BigSur, cmdstanpy==0.9.5, python, I've tried both the 3.8.6 and 3.9.1

Thanks for checking this.
