### ISSUE TITLE
RuntimeError: Error during generate_quantities retcodes=[3221225477]

### ISSUE THREAD

**Issue by gregorp90** [stan-dev/cmdstanpy#459]
#### Summary:
Hi all, I'm trying to use the `generate_quantities` function of the CmdStanModel class. The model compiles, however, once I run it I get some runtime errors that are not very helpful in debugging.

#### Description:
I'm running hierarchical stacking on relatively large data sets, so I would like to use an already sampled model to generate predictions. I tried running the code described here: https://mc-stan.org/cmdstanpy/examples/Run%20Generated%20Quantities.html, which works perfectly fine. However, once I try to apply it to my problem, I get the following error:
```
new_quantities = hstack_ppc_model.generate_quantities(data=hstack_data, mcmc_sample=hstack_fit)
INFO:cmdstanpy:start chain 1
INFO:cmdstanpy:finish chain 1
ERROR:cmdstanpy:Chain 1 processing error, non-zero return code 3221225477
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-c21edc63150d>", line 1, in <module>
    new_quantities = hstack_ppc_model.generate_quantities(data=hstack_data, mcmc_sample=hstack_fit)
  File "C:\Anaconda3\lib\site-packages\cmdstanpy\model.py", line 990, in generate_quantities
    raise RuntimeError(msg)
RuntimeError: Error during generate_quantities:
Command and output files:
RunSet: chains=1
 cmd:
	['E:/shared_files_e/Gregor/gq-problem/hstack_ppc.exe', 'id=1', 'random', 'seed=8051', 'data', 'file=C:\\Users\\Gregor\\AppData\\Local\\Temp\\tmp101s6tue\\kk9sd6ws.json', 'output', 'file=C:\\Users\\Gregor\\AppData\\Local\\Temp\\tmp101s6tue\\hstack_ppc-202109201615-1-baz2k23v.csv', 'method=generate_quantities', 'fitted_params=C:\\Users\\Gregor\\AppData\\Local\\Temp\\tmp101s6tue\\hstack-202109201615-1-i2f4k2ei.csv']
 retcodes=[3221225477]
 csv_files:
	C:\Users\Gregor\AppData\Local\Temp\tmp101s6tue\hstack_ppc-202109201615-1-baz2k23v.csv
 console_msgs:
	C:\Users\Gregor\AppData\Local\Temp\tmp101s6tue\hstack_ppc-202109201615-1-baz2k23v-stdout.txt
```

I am unable to decipher this error message. The only thing that changed from the Bernoulli example is that _hstack.stan_ model uses matrices and a transformed data block. I'm attaching a minimal example. I also tried running `sample` for the model with generated quantities (_hstack_ppc.stan_) and it works, so the problem is only in running `generated_quantities` with an already sampled model. Hopefully, I'm not missing something obvious.

As a workaround I could generate new quantities outside of Stan, however, I would prefer using Stan if possible.

#### Additional Information:
This happened on two separate machines with versions 0.9.76 and 0.9.77 of cmdstanpy. Both machines run Windows 10.

#### Current Version
0.9.76/0.9.77

#### Attachments
[gq-problem.zip](https://github.com/stan-dev/cmdstanpy/files/7196445/gq-problem.zip)

**Comment by WardBrian** [comment]
Running this straight from the command line:

```
$ ./hstack sample data file=data.json
method = sample (Default)
  sample
    num_samples = 1000 (Default)
    num_warmup = 1000 (Default)
    save_warmup = 0 (Default)
    thin = 1 (Default)
    adapt
      engaged = 1 (Default)
      gamma = 0.050000000000000003 (Default)
      delta = 0.80000000000000004 (Default)
      kappa = 0.75 (Default)
      t0 = 10 (Default)
      init_buffer = 75 (Default)
      term_buffer = 50 (Default)
      window = 25 (Default)
    algorithm = hmc (Default)
      hmc
        engine = nuts (Default)
          nuts
            max_depth = 10 (Default)
        metric = diag_e (Default)
        metric_file =  (Default)
        stepsize = 1 (Default)
        stepsize_jitter = 0 (Default)
id = 0 (Default)
data
  file = data.json
init = 2 (Default)
random
  seed = 183143309 (Default)
output
  file = output.csv (Default)
  diagnostic_file =  (Default)
  refresh = 100 (Default)
  sig_figs = -1 (Default)
  profile_file = profile.csv (Default)


Gradient evaluation took 3.5e-05 seconds
1000 transitions using 10 leapfrog steps per transition would take 0.35 seconds.
Adjust your expectations accordingly!


Iteration:    1 / 2000 [  0%]  (Warmup)
Iteration:  100 / 2000 [  5%]  (Warmup)
Iteration:  200 / 2000 [ 10%]  (Warmup)
Iteration:  300 / 2000 [ 15%]  (Warmup)
Iteration:  400 / 2000 [ 20%]  (Warmup)
Iteration:  500 / 2000 [ 25%]  (Warmup)
Iteration:  600 / 2000 [ 30%]  (Warmup)
Iteration:  700 / 2000 [ 35%]  (Warmup)
Iteration:  800 / 2000 [ 40%]  (Warmup)
Iteration:  900 / 2000 [ 45%]  (Warmup)
Iteration: 1000 / 2000 [ 50%]  (Warmup)
Iteration: 1001 / 2000 [ 50%]  (Sampling)
Iteration: 1100 / 2000 [ 55%]  (Sampling)
Iteration: 1200 / 2000 [ 60%]  (Sampling)
Iteration: 1300 / 2000 [ 65%]  (Sampling)
Iteration: 1400 / 2000 [ 70%]  (Sampling)
Iteration: 1500 / 2000 [ 75%]  (Sampling)
Iteration: 1600 / 2000 [ 80%]  (Sampling)
Iteration: 1700 / 2000 [ 85%]  (Sampling)
Iteration: 1800 / 2000 [ 90%]  (Sampling)
Iteration: 1900 / 2000 [ 95%]  (Sampling)
Iteration: 2000 / 2000 [100%]  (Sampling)

 Elapsed Time: 0.077 seconds (Warm-up)
               0.085 seconds (Sampling)
               0.162 seconds (Total)


$ ./hstack_ppc generate_quantities fitted_params=output.csv output file=ppc.csv data file=data.json

method = generate_quantities
  generate_quantities
    fitted_params = output.csv
id = 0 (Default)
data
  file = data.json
init = 2 (Default)
random
  seed = 183146268 (Default)
output
  file = ppc.csv
  diagnostic_file =  (Default)
  refresh = 100 (Default)
  sig_figs = -1 (Default)
  profile_file = profile.csv (Default)

Segmentation fault (core dumped)

```

It seems like you've found not just a cmdstanpy issue, but a cmdstan issue. @mitzimorris - should we transfer this issue?

**Comment by ahartikainen** [comment]
We really need a function to print stdout csv

**Comment by WardBrian** [comment]
I know Mitzi is re-writing how we handle stdout and stderr right now
