### ISSUE TITLE
Using external C++ functions not working

### ISSUE THREAD

**Issue by mvidela31** [stan-dev/cmdstanpy#521]
#### Summary:
The CmdStanPy example: "Advanced Topic: Using External C++ Functions" is not working.

#### Description:
I tried to follow the example provided in the docs to incorporate external C++ functions into Stan's models, but the example itself has runtime errors (which I also replicate). Is it a bug of the current CmdStanPy version, or is this advanced functionality still under development?

#### Additional Information:
Link: [Advanced Topic: Using External C++ Functions](https://mc-stan.org/cmdstanpy/examples/Using%20External%20C%2B%2B.html)

#### Current Version:
CmdStanPy 1.0.0

**Comment by WardBrian** [comment]
I'm not able to recreate this locally, not sure why the docs are broken. They're correct on readthedocs: https://cmdstanpy.readthedocs.io/en/v1.0.0rc1/examples/Using%20External%20C%2B%2B.html

Do you have a copy of `make_odds.hpp` in the same folder as the Stan files?

**Comment by mvidela31** [comment]
Yes, the `make_odds.hpp`, `bernoulli_external.stan` and the `.py` files are all in the same folder. Trying to debugging this issue, I realize that the current folder path changes to the Anaconda environment path after the CmdStanModel is instantiated (I followed the [recommended installation for conda users](https://mc-stan.org/cmdstanpy/installation.html)), but manually writing the absolute paths of both files doesn't solve the problem either (the model still doesn't compile, but now without output errors).

Here is my test code:
```Python
import os
from cmdstanpy import CmdStanModel

print(os.path.abspath('.'))
model_external = CmdStanModel(stan_file='bernoulli_external.stan', compile=False)
print(os.path.abspath('.'))
model_external.compile(user_header='make_odds.hpp')
```
And here is the corresponding output:
```Python
/home/miguel/Desktop/Bayesian_inference-SB1/cmdstan/example2
/home/miguel/anaconda3/envs/cmdstan/bin/cmdstan

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <module>
      5 model_external = CmdStanModel(stan_file='bernoulli_external.stan', compile=False)
      6 print(os.path.abspath('.'))
----> 7 model_external.compile(user_header='make_odds.hpp')

File ~/anaconda3/envs/cmdstan/lib/python3.8/site-packages/cmdstanpy/model.py:370, in CmdStanModel.compile(self, force, stanc_options, cpp_options, user_header, override_options)
    360 if (
    361     stanc_options is not None
    362     or cpp_options is not None
    363     or user_header is not None
    364 ):
    365     compiler_options = CompilerOptions(
    366         stanc_options=stanc_options,
    367         cpp_options=cpp_options,
    368         user_header=user_header,
    369     )
--> 370     compiler_options.validate()
    372     if compiler_options != self._compiler_options:
    373         force = True

File ~/anaconda3/envs/cmdstan/lib/python3.8/site-packages/cmdstanpy/compiler_opts.py:112, in CompilerOptions.validate(self)
    110 self.validate_stanc_opts()
    111 self.validate_cpp_opts()
--> 112 self.validate_user_header()

File ~/anaconda3/envs/cmdstan/lib/python3.8/site-packages/cmdstanpy/compiler_opts.py:186, in CompilerOptions.validate_user_header(self)
    181 if self._user_header != "":
    182     if not (
    183         os.path.exists(self._user_header)
    184         and os.path.isfile(self._user_header)
    185     ):
--> 186         raise ValueError(
    187             f"User header file {self._user_header} cannot be found"
    188         )
    189     if self._user_header[-4:] != '.hpp':
    190         raise ValueError(
    191             f"Header file must end in .hpp, got {self._user_header}"
    192         )

ValueError: User header file make_odds.hpp cannot be found
```

**Comment by WardBrian** [comment]
Ah, my guess is this is caused by #506

If you try to do it without the command that fails occurring first, does it work?

**Comment by mvidela31** [comment]
The command that fails is ```model_external.compile(user_header='make_odds.hpp')```, 
not `model_external = CmdStanModel(stan_file='bernoulli_external.stan', compile=False)` (since the compilation is avoided). 

I tried to compile the model with the header all at once (```model_external = CmdStanModel(stan_file='bernoulli_external.stan', user_header='make_odds.hpp')```), but this shows the same error (```ValueError: User header file make_odds.hpp cannot be found```). I also tried the same but writing the absolute paths explicitly. Unfortunately, this still doesn't work :disappointed::
```Python
INFO:cmdstanpy:compiling stan file /home/miguel/Desktop/Bayesian_inference-SB1/cmdstan/example2/bernoulli_external.stan to exe file /home/miguel/Desktop/Bayesian_inference-SB1/cmdstan/example2/bernoulli_external
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    model_external = CmdStanModel(stan_file='/home/miguel/Desktop/Bayesian_inference-SB1/cmdstan/example2/bernoulli_external.stan', user_header='/home/miguel/Desktop/Bayesian_inference-SB1/cmdstan/example2/make_odds.hpp')
  File "/home/miguel/anaconda3/envs/cmdstan/lib/python3.8/site-packages/cmdstanpy/model.py", line 215, in __init__
    raise ValueError(
ValueError: Unable to compile Stan model file: /home/miguel/Desktop/Bayesian_inference-SB1/cmdstan/example2/bernoulli_external.stan.
```

**Comment by mvidela31** [comment]
I tried to run the code using the develop branch (installing it using the command `pip install -e git+https://github.com/stan-dev/cmdstanpy@develop#egg=cmdstanpy` in the base environment), but the compilation problem persists.
* **Test code:**
```Python
from cmdstanpy import CmdStanModel

model_external = CmdStanModel(stan_file='bernoulli_external.stan', compile=False)
model_external.compile(user_header='make_odds.hpp')
fit = model_external.sample(data={'N':10, 'y':[0,1,0,0,0,0,0,0,0,1]})
fit.stan_variable('odds')
```
* **Console output using the release branch (CmdStanPy 1.0.0):**
```Python
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    model_external.compile(user_header='make_odds.hpp')
  File "/home/miguel/anaconda3/envs/cmdstan/lib/python3.8/site-packages/cmdstanpy/model.py", line 370, in compile
    compiler_options.validate()
  File "/home/miguel/anaconda3/envs/cmdstan/lib/python3.8/site-packages/cmdstanpy/compiler_opts.py", line 112, in validate
    self.validate_user_header()
  File "/home/miguel/anaconda3/envs/cmdstan/lib/python3.8/site-packages/cmdstanpy/compiler_opts.py", line 186, in validate_user_header
    raise ValueError(
ValueError: User header file make_odds.hpp cannot be found
INFO:cmdstanpy:deleting tmpfiles dir: /tmp/tmpxqvwsqvz
INFO:cmdstanpy:done
```
* **Console output using the develop branch:**
```Python
INFO:cmdstanpy:compiling stan file /home/miguel/Desktop/Bayesian_inference-SB1/cmdstan/example2/bernoulli_external.stan to exe file /home/miguel/Desktop/Bayesian_inference-SB1/cmdstan/example2/bernoulli_external
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    fit = model_external.sample(data={'N':10, 'y':[0,1,0,0,0,0,0,0,0,1]})
  File "/home/miguel/src/cmdstanpy/cmdstanpy/model.py", line 940, in sample
    refresh=refresh,
  File "/home/miguel/src/cmdstanpy/cmdstanpy/cmdstan_args.py", line 743, in __init__
    self.validate()
  File "/home/miguel/src/cmdstanpy/cmdstanpy/cmdstan_args.py", line 757, in validate
    raise ValueError('model not compiled')
ValueError: model not compiled
INFO:cmdstanpy:deleting tmpfiles dir: /tmp/tmpmvom4wrz
INFO:cmdstanpy:done
```
Note that now the path problems seems to be fixed, but it could be due to the installation was performed in the base environment. Anyways, the model still doesn't compile.

**Comment by WardBrian** [comment]
This is very strange. For me I get the following (sucessful) output:

```python
>>> from cmdstanpy import *
>>> model_external = CmdStanModel(stan_file='bernoulli_external.stan', compile=False)
>>> model_external.compile(user_header='make_odds.hpp')
INFO:cmdstanpy:compiling stan file /home/brian/Dev/py/cmdstanpy/docsrc/examples/bernoulli_external.stan to exe file /home/brian/Dev/py/cmdstanpy/docsrc/examples/bernoulli_external
INFO:cmdstanpy:compiled model executable: /home/brian/Dev/py/cmdstanpy/docsrc/examples/bernoulli_external
>>> fit = model_external.sample(data={'N':10, 'y':[0,1,0,0,0,0,0,0,0,1]})
INFO:cmdstanpy:CmdStan start processing
chain 1 |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 00:00 Sampling completed
chain 2 |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 00:00 Sampling completed
chain 3 |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 00:00 Sampling completed
chain 4 |█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 00:00 Sampling completed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
INFO:cmdstanpy:CmdStan done processing.
>>> fit.stan_variable('odds')
array([0.783381, 0.76832 , 0.849141, ..., 0.260408, 0.330346, 0.315762])
```


Our example is taken more or less directly from the [CmdStan documentation](https://mc-stan.org/docs/2_28/cmdstan-guide/using-external-cpp-code.html) - are you able to run the shell commands there directly to produce a compiled model?

**Comment by WardBrian** [comment]
@mvidela31 have you had the opportunity to try this using only CmdStan?

**Comment by mvidela31** [comment]
Hi @WardBrian, sorry for the delay.

I finally realized that my compilation error is due to a name mismatch in the ```makes_odds.hpp``` file. The namespace declaration has to match with the corresponding ```.stan``` filename:
```C++
#include <boost/math/tools/promotion.hpp>
#include <ostream>

namespace <STAN_FILENAME>_model_namespace {
    template <typename T0__>  inline  typename
          boost::math::tools::promote_args<T0__>::type
          make_odds(const T0__& theta, std::ostream* pstream__) {
            return theta / (1 - theta);
       }
}
```
By modifying the namespace I was able to run the example successfully in both the CmdStan and the CmdStanPy (develop branch) inferfaces:
```Shell
(cmdstan2) miguel@miguel-ASUS-Laptop-X407UBR:~/Desktop/cmdstan/bernoulli_external$ python example2.py
INFO:cmdstanpy:compiling stan file /home/miguel/Desktop/cmdstan/bernoulli_external/bernoulli_external.stan to exe file /home/miguel/Desktop/cmdstan/bernoulli_external/bernoulli_external
INFO:cmdstanpy:compiled model executable: /home/miguel/Desktop/cmdstan/bernoulli_external/bernoulli_external
INFO:cmdstanpy:CmdStan start processing
chain 1 |███████████████████████████████████████████████████████████████████████████████████████████████████████████| 00:00 Sampling completed
chain 2 |███████████████████████████████████████████████████████████████████████████████████████████████████████████| 00:00 Sampling completed
chain 3 |███████████████████████████████████████████████████████████████████████████████████████████████████████████| 00:00 Sampling completed
chain 4 |███████████████████████████████████████████████████████████████████████████████████████████████████████████| 00:00 Sampling completed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
INFO:cmdstanpy:CmdStan done processing.
INFO:cmdstanpy:deleting tmpfiles dir: /tmp/tmp69ofslue
INFO:cmdstanpy:done
```
Thanks and sorry for bothering you :sweat_smile:.

**Comment by WardBrian** [comment]
No worries, glad it is working!

This difficulty of namespacing is a known issue with the user headers in CmdStan. I believe the RStan interface actually solves it by injecting the user-supplied C++ inside the generated model class, and I think CmdStan considered doing this but decided not to

**Comment by mitzimorris** [comment]
no need to apologize - glad you figured this out and thanks for sharing!
