### ISSUE TITLE
Windows 10 compile error

### ISSUE THREAD

**Issue by shadowcrow0** [stan-dev/cmdstanpy#643]
#### Summary:
I use windows 10 to run cmdstanpy, and I got the error below.

#### Description:
16:56:48 - cmdstanpy - INFO - compiling stan file C:\Users\xxx\.conda\envs\stan\lnrm2_v2.stan to exe file C:\Users\xxx\.conda\envs\stan\lnrm2_v2.exe
Traceback (most recent call last):
  File "C:/Users/xxx/.conda/envs/stan/dotstudy_ver4(5).py", line 762, in <module>
    prx_levels = find_salience(dat_prx, 3, 1)
  File "C:\Users\xxx\.conda\envs\stan\adaptive_SFT.py", line 194, in find_salience
    sm = CmdStanModel(stan_file="lnrm2_v2.stan")
  File "C:\Users\xxx\AppData\Roaming\Python\Python38\site-packages\cmdstanpy\model.py", line 213, in init
    self.compile(force=str(compile).lower() == 'force')
  File "C:\Users\xxx\AppData\Roaming\Python\Python38\site-packages\cmdstanpy\model.py", line 550, in compile
    raise ValueError(
ValueError: Failed to compile Stan model 'C:\Users\xxx\.conda\envs\stan\lnrm2_v2.stan'. Console:

Command: ['mingw32-make', 'C:/Users/LoraC/.conda/envs/stan/lnrm2_v2.exe']
failed with error [WinError 2] The system cannot find the file specified

#### Additional Information:
Provide any additional information here.

#### Current Version:
Please include the output of `import cmdstanpy; cmdstanpy.show_versions()`, or
at least the cmdstan and cmdstanpy versions used.
cmdstan: (2, 31)
cmdstanpy: 1.0.8

This stan file is located
"C:\Users\xxx\Dropbox\2022Fall\dotstudy-master\data\dotstudy"

I am not familiar with Path. would you mind to tell me which part I should place in
CmdStanModel(stan_file=Path(__file__).parent/"lnrm2_v2.stan")

Thanks

**Comment by ahartikainen** [comment]
where are these stan files located?

    CmdStanModel(stan_file="lnrm2_v2.stan")

Maybe you need to add path to them

    CmdStanModel(stan_file=Path(__file__"lnrm2_v2.stan")

**Comment by shadowcrow0** [comment]
> where are these stan files located?
> 
> ```
> CmdStanModel(stan_file="lnrm2_v2.stan")
> ```
> 
> Maybe you need to add path to them
> 
> ```
> CmdStanModel(stan_file=Path(__file__).parent/"lnrm2_v2.stan")
> ```


This stan file is located
"C:\Users\xxx\Dropbox\2022Fall\dotstudy-master\data\dotstudy"

I am not familiar with Path. would you mind to tell me which part I should place in
`CmdStanModel(stan_file=Path(__file__).parent/"lnrm2_v2.stan")`


Thanks

**Comment by tomfid** [comment]
I'm seeing the same error, also win10. I haven't traced it back to the root cause yet, but I think it's a platform incompatibility with the makefile. I'm using 2.31.0.

I'm calling from stanify, but I've issued the same command from a cmd prompt, using the same cwd:

`mingw32-make STANCFLAGS+=--include-paths=C:/bayes/git/stanify/vignette/stan_files/hier_preypredator C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.exe`

The output is:

```
'cut' is not recognized as an internal or external command,
operable program or batch file.
'cut' is not recognized as an internal or external command,
operable program or batch file.
process_begin: CreateProcess(NULL, expr >= 8, ...) failed.
mingw32-make: makefile:125: pipe: Bad file descriptor
INFO: Could not find files for the given pattern(s).
''
'--- Translating Stan model to C++ code ---'
bin/stanc.exe --include-paths=C:/bayes/git/stanify/vignette/stan_files/hier_preypredator --o=C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.hpp C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.stan
''
'--- Compiling, linking C++ code ---'
g++ -std=c++1y -m64 -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs -Wno-int-in-bool-context -Wno-attributes -Wno-ignored-attributes -I stan/lib/stan_math/lib/tbb_2020.3/include -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -D_USE_MATH_DEFINES -DBOOST_DISABLE_ASSERTS -c -x c++ -o C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.o C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.hpp
g++ -std=c++1y -m64 -D_REENTRANT -Wall -Wno-unused-function -Wno-uninitialized -Wno-unused-but-set-variable -Wno-unused-variable -Wno-sign-compare -Wno-unused-local-typedefs -Wno-int-in-bool-context -Wno-attributes -Wno-ignored-attributes -I stan/lib/stan_math/lib/tbb_2020.3/include -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials -D_USE_MATH_DEFINES -DBOOST_DISABLE_ASSERTS -Wl,-L,"c:/Users/tom/.cmdstan/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"c:/Users/tom/.cmdstan/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb" C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.o src/cmdstan/main.o -static-libgcc -static-libstdc++ -Wl,-L,"c:/Users/tom/.cmdstan/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb" -Wl,-rpath,"c:/Users/tom/.cmdstan/cmdstan-2.31.0/stan/lib/stan_math/lib/tbb" stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_nvecserial.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_cvodes.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_idas.a stan/lib/stan_math/lib/sundials_6.1.1/lib/libsundials_kinsol.a stan/lib/stan_math/lib/tbb/tbb.dll -o C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.exe
rm -f C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.o
process_begin: CreateProcess(NULL, rm -f C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.o, ...) failed.
make (e=2): The system cannot find the file specified.
mingw32-make: *** [make/program:60: C:/bayes/git/stanify/vignette/stan_files/hier_preypredator/draws2data_hier_preypredator.exe] Error 2
```

I think the 'cut' errors are a distraction - they seem to come from a piped command,
CXX_MAJOR :=(CXX) -dumpversion 2>&1 | cut -d'.' -f1)
The consequence of CXX_MAJOR being undefined is a couple flag changes and the error at 125.

It seems like the real issue is the attempt to rm -f the .o file. The file exists, but rm is the linux shell command; the dos equivalent would be del. The obvious workaround would be to comment out that line, because it's nonvital cleanup, but I haven't worked out where it originates - it's not in the top level makefile, so it must be in one of the includes.

**Comment by WardBrian** [comment]
Not having `cut` and `rm` installed to me suggests you have an incomplete MingW installation. Did you manually install the C++ compiler and `mingw32-make`?

If you installed via cmdstanpy (e.g. with `python -m cmdstanpy.install_cmdstan --compiler`) it should have ensured you had copies of both `rm` and `cut`.

**Comment by tomfid** [comment]
Makes sense. I installed via the PyCharm package manager, which may not have been equivalent. I'll check.

**Comment by tomfid** [comment]
Building inside python, but hard to tell on the manual make, because after the python failure I think I modified the system path manually before testing. Too many possible permutations.

**Comment by tomfid** [comment]
I'm guessing that the py install via
cmdstanpy.install_cmdstan(compiler=True)  # only valid on Windows
is volatile, i.e. it modifies the system path only in the context of the current run?

**Comment by WardBrian** [comment]
I'm closing this due to lack of activity, please re-open if this issue is still occurring.
