### ISSUE TITLE
Model fails to compile when using OPEN_CL

### ISSUE THREAD

**Issue by theonlydvr** [stan-dev/cmdstanpy#651]
#### Summary:
When setting the OPEN_CL flag for compilation to true, compilation fails.

#### Description:
Compilation fails for a model that previously compiled when attempting to use OPEN_CL.

#### Additional Information:
I get the following error message:

```
15:27:17 - cmdstanpy - INFO - compiling stan file C:\Users\Evan\Documents\GitHub\RLDDM\FARLDDM.stan to exe file C:\Users\Evan\Documents\GitHub\RLDDM\FARLDDM.exe
Traceback (most recent call last):
  File "C:\Users\Evan\Documents\GitHub\RLDDM\run.py", line 11, in <module>
    model = CmdStanModel(stan_file=stan_file, compile="force", cpp_options={'STAN_THREADS': 'true'})
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Evan\.conda\envs\stan\Lib\site-packages\cmdstanpy\model.py", line 236, in __init__
    self.compile(force=str(compile).lower() == 'force')
  File "C:\Users\Evan\.conda\envs\stan\Lib\site-packages\cmdstanpy\model.py", line 563, in compile
    raise ValueError(
ValueError: Failed to compile Stan model 'C:\Users\Evan\Documents\GitHub\RLDDM\FARLDDM.stan'. Console:

--- Compiling the main object file. This might take up to a minute. ---
mkdir: cannot create directory 'src': No such file or directory
make/program:11: recipe for target 'src/cmdstan/main_threads_opencl.o' failed
mingw32-make: *** [src/cmdstan/main_threads_opencl.o] Error 1

Command ['mingw32-make', 'STAN_THREADS=true', 'C:/Users/Evan/Documents/GitHub/RLDDM/FARLDDM.exe']
	error during processing No such file or directory


Process finished with exit code 1

```

I installed stan via conda after setting up the CUDA installation and graphics drivers.
clinfo confirms OPEN_CL is properly installed.

#### Current Version:

```
python: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:12:32) [MSC v.1929 64 bit (AMD64)]
python-bits: 64
OS: Windows
OS-release: 10
machine: AMD64
processor: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None
LOCALE: ('English_United States', '1252')
cmdstan_folder: C:\Users\Evan\.conda\envs\stan\Library\bin\cmdstan
cmdstan: (2, 31)
cmdstanpy: 1.1.0
pandas: 1.5.3
xarray: 2023.2.0
tqdm: 4.64.1
numpy: 1.24.2
```

**Comment by WardBrian** [comment]
I believe this is an issue specific to the Conda installation on Windows. If you're able to open an issue here instead: https://github.com/conda-forge/cmdstan-feedstock

For now you may wish to try installing CmdStan from source
