### ISSUE TITLE
please rebuild precompiled header 'stan/src/stan/model/model_header.hpp.gch' buries instructions

### ISSUE THREAD

**Issue by bob-carpenter** [stan-dev/cmdstanpy#674]
#### Summary:

I found this so confusing that I started an issue.  The instructions for a fix are printed up front, but then quickly scrolled offscreen by the dump from CmdStan.  I'm left seeing this at the bottom of the dump:

```python
note: please rebuild precompiled header 'stan/src/stan/model/model_header.hpp.gch'
```

Would there be a way to convert the WARNING into FATAL error and then suppress all the CmdStan output which won't be interpretable to a CmdStanPy user?  There's also a missing space after the period, but the message is so long it scrolls off the screen to the right in the dump (you can scroll over):

```python
>>> model = csp.CmdStanModel(stan_file = 'funnel-ctr.stan')
11:41:11 - cmdstanpy - INFO - compiling stan file /Users/bcarpenter/temp2/funnel-ctr.stan to exe file /Users/bcarpenter/temp2/funnel-ctr
11:41:30 - cmdstanpy - WARNING - CmdStan's precompiled header (PCH) files may need to be rebuilt.Please run cmdstanpy.rebuild_cmdstan().
If the issue persists please open a bug report
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/cmdstanpy/model.py", line 236, in __init__
    self.compile(force=str(compile).lower() == 'force')
  File "/usr/local/lib/python3.9/site-packages/cmdstanpy/model.py", line 563, in compile
    raise ValueError(
ValueError: Failed to compile Stan model '/Users/bcarpenter/temp2/funnel-ctr.stan'. Console:

--- Translating Stan model to C++ code ---
bin/stanc  --o=/Users/bcarpenter/temp2/funnel-ctr.hpp /Users/bcarpenter/temp2/funnel-ctr.stan

--- Compiling, linking C++ code ---
clang++ -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2020.3/include    -O3 -I src -I stan/src -I stan/lib/rapidjson_1.1.0/ -I lib/CLI11-1.9.1/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.9 -I stan/lib/stan_math/lib/boost_1.78.0 -I stan/lib/stan_math/lib/sundials_6.1.1/include -I stan/lib/stan_math/lib/sundials_6.1.1/src/sundials    -DBOOST_DISABLE_ASSERTS          -c -include-pch stan/src/stan/model/model_header.hpp.gch -x c++ -o /Users/bcarpenter/temp2/funnel-ctr.o /Users/bcarpenter/temp2/funnel-ctr.hpp
fatal error: file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/__functional/invoke.h' has been modified since the precompiled header 'stan/src/stan/model/model_header.hpp.gch' was built: mtime changed (was 1677962806, now 1677952029)
note: please rebuild precompiled header 'stan/src/stan/model/model_header.hpp.gch'
1 error generated.
make: *** [/Users/bcarpenter/temp2/funnel-ctr] Error 1

Command ['make', '/Users/bcarpenter/temp2/funnel-ctr']
	error during processing No such file or directory
```

#### Current Version:

```python
>>> csp.show_versions()
INSTALLED VERSIONS
---------------------
python: 3.9.4 (default, Apr  5 2021, 01:47:16) 
[Clang 11.0.0 (clang-1100.0.33.17)]
python-bits: 64
OS: Darwin
OS-release: 22.5.0
machine: x86_64
processor: i386
byteorder: little
LC_ALL: None
LANG: en_US.UTF-8
LOCALE: ('en_US', 'UTF-8')
cmdstan_folder: /Users/bcarpenter/.cmdstan/cmdstan-2.31.0
cmdstan: (2, 31)
cmdstanpy: 1.1.0
pandas: 1.4.3
xarray: 2023.1.0
tqdm: 4.64.0
numpy: 1.24.1

' '
```

**Comment by bob-carpenter** [comment]
By false negatives and positives, do you mean that Stan will print out a WARNING message that is wrong?  If that's the case, then you can't make it an ERROR.   I've never seen it come up other than forcing me to rebuild precompiled headers, but I always have a hard time finding the command to do it among the output.  And I think if we can catch this reliably, we'd just want to stop early with a warning message.  But if this is all impossible, then please just close this issue.  Thanks.

**Comment by WardBrian** [comment]
Yes. Because there is not a consistent error message generated by the compiler, we have the somewhat loose bounds of checking if the string `PCH` or `precompiled header` appear in the output:
https://github.com/stan-dev/cmdstanpy/blob/acd557f5b8d882f920e6126e88c42dc041677da2/cmdstanpy/model.py#L556

However, this has previously generated instances where we suggest recompiling when the actual issue was something else. On the whole it seems like the warning is more helpful than not, but displaying the entire output is a useful fall-back for debugging
