### ISSUE TITLE
update logo on docs

### ISSUE THREAD

**Issue by mitzimorris** [stan-dev/cmdstanpy#742]
#### Summary:
Use new Stan logo everywhere - https://github.com/stan-dev/logos/blob/master/logo_name.png

**Comment by mitzimorris** [comment]
I'm getting a wierd build error -

```


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/Users/mitzi/miniconda3/envs/stan/lib/python3.11/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/Users/mitzi/github/stan-dev/cmdstanpy/docsrc/conf.py", line 146, in <module>
    from cmdstanpy import __version__
  File "/Users/mitzi/github/stan-dev/cmdstanpy/cmdstanpy/__init__.py", line 25, in <module>
    from .compilation import compile_stan_file, format_stan_file
  File "/Users/mitzi/github/stan-dev/cmdstanpy/cmdstanpy/compilation.py", line 16, in <module>
    from cmdstanpy.utils import get_logger
  File "/Users/mitzi/github/stan-dev/cmdstanpy/cmdstanpy/utils/__init__.py", line 32, in <module>
    from .stancsv import (
  File "/Users/mitzi/github/stan-dev/cmdstanpy/cmdstanpy/utils/stancsv.py", line 10, in <module>
    import pandas as pd
  File "/Users/mitzi/miniconda3/envs/stan/lib/python3.11/site-packages/pandas/__init__.py", line 19, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
dateutil: No module named 'dateutil'

```

**Comment by WardBrian** [comment]
Are you able to import pandas normally? That error doesn't seem directly related to the docs

**Comment by WardBrian** [comment]
I think you'd be missing `cmdstan`. 

But the `--clone base` is suspect to me - if you already had a copy of pandas (potentially a broken one, for whatever reason) you'd end up with it in here as well.

**Comment by mitzimorris** [comment]
OK, the problem is that you need to install pandas via conda - installing pandas using pip doesn't get the libraries needed for dateutil.

```
(stan) ~/github/stan-dev/cmdstanpy (develop)> conda install pandas
Channels:
 - conda-forge
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/mitzi/miniconda3/envs/stan

  added / updated specs:
    - pandas


The following NEW packages will be INSTALLED:

  libblas            conda-forge/osx-64::libblas-3.9.0-21_osx64_openblas 
  libcblas           conda-forge/osx-64::libcblas-3.9.0-21_osx64_openblas 
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-13_2_0_h97931a8_3 
  libgfortran5       conda-forge/osx-64::libgfortran5-13.2.0-h2873a65_3 
  liblapack          conda-forge/osx-64::liblapack-3.9.0-21_osx64_openblas 
  libopenblas        conda-forge/osx-64::libopenblas-0.3.26-openmp_hfef2a42_0 
  llvm-openmp        conda-forge/osx-64::llvm-openmp-18.1.2-hb6ac08f_0 
  numpy              conda-forge/osx-64::numpy-1.26.4-py311hc43a94b_0 
  pandas             conda-forge/osx-64::pandas-2.2.1-py311h8f6166a_0 
  python-dateutil    conda-forge/noarch::python-dateutil-2.9.0-pyhd8ed1ab_0 
  python-tzdata      conda-forge/noarch::python-tzdata-2024.1-pyhd8ed1ab_0 
  pytz               conda-forge/noarch::pytz-2024.1-pyhd8ed1ab_0 
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 

```
